format = """
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$memory_usage\
$cmd_duration\
$character"""

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[package]
disabled = true

[sudo]
style = 'bold green'
disabled = false

[memory_usage]
format='RAM: [${ram_pct}]($style) '
disabled = false
threshold = 60
symbol = ''
style = 'bold red'

[line_break]
disabled = false

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) [$hostname](bold purple) '
disabled = false

[git_metrics]
format = '[+$added](bright-green)/[-$deleted](bright-red) '
only_nonzero_diffs=true
disabled = false

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[🍒 PICKING](bold red)'
