format = """
$shlvl\
$singularity\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$nix_shell\
$memory_usage\
$env_var\
$cmd_duration\
$line_break\
$battery\
$time\
$status\
$os\
$character"""

"$schema" = 'https://starship.rs/config-schema.json'
add_newline = true

[package]
disabled = true
